version: '3.7'

networks:
  default:
    external:
      name: whirlpool-net


services:

  whirlpool-due:
    container_name: whirlpool-due
    entrypoint: bash ./scripts/wait-for-it.sh
    environment:
      - PY_ENV=development
    build:
      context: ./
      dockerfile: Dockerfile
      target: whirlpool-due-dev
    restart: on-failure
